stages:
  - build
  - test

image: ${CI_REGISTRY}/khassel/container/kaniko:latest

variables:
  GIT_DEPTH: 1

.jobext:
  rules:
  - if: $CI_COMMIT_BRANCH =~ /^(master|develop)$/
  tags:
  - docker

build:
  stage: build
  script:
  - ./bin/build.sh
  extends: .jobext
  parallel:
    matrix:
      - imgarch: ["amd64", "arm"]

test_amd64:
  stage: test
  needs: ["build: [amd64]"]
  variables:
    GIT_STRATEGY: none
    StartEnv: test
  image: 
    name: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}_amd64
    entrypoint: [""]
  script:
  - /opt/magic_mirror/entrypoint.sh
  extends: .jobext
