stages:
  - build
  - test

image:
  name: ${DOCKER_USER}/kaniko-executor:latest
  entrypoint: [""]

variables:
  GIT_DEPTH: 1

.jobext:
  after_script:
  - docker.logout
  rules:
  - if: $CI_COMMIT_BRANCH =~ /^(master|develop)$/
  tags:
  - docker

.build:
  stage: build
  script:
  - ./bin/build.sh ${CI_COMMIT_BRANCH} ${buildarch}
  extends: .jobext

build_amd64:
  extends: .build

build_arm:
  variables:
    buildarch: "arm32v7/"
  extends: .build

build_alpine:
  stage: test
  needs: ["build_amd64"]
  script:
  - ./bin/build_alpine.sh ${CI_COMMIT_BRANCH}
  extends: .jobext

test_amd64:
  stage: test
  needs: ["build_amd64"]
  variables:
    GIT_STRATEGY: none
  image:
    name: ${DOCKER_USER}/magicmirror:${CI_COMMIT_BRANCH}_amd64
    entrypoint: [""]
  script:
  - StartEnv=test /opt/magic_mirror/entrypoint.sh
  extends: .jobext
