image: docker:stable

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: "1"
  DOCKER_USER: "karsten13"

services:
- docker:dind

before_script:
- docker info
# install docker-compose
- apk add --no-cache py-pip curl
- pip install docker-compose
- docker-compose version
- curl -L -O https://github.com/docker-slim/docker-slim/releases/download/1.23/dist_linux.tar.gz
- tar -zxvf dist_linux.tar.gz
- ./dist_linux/docker-slim version

.build: &do_build
  script:
  - echo "MyBuildEnv="$MyBuildEnv
  - ./prepare_env $MyBuildEnv
  # get variables from .env
  - export $(cat .env | grep -v ^# | xargs)
  - echo "BuildEnv="$BuildEnv;
  - echo "myimage="$myimage;
  - echo "MagicMirror_Version="$MagicMirror_Version;
  # build image
  - cd ./build
  - |
    if [ "$BuildEnv" = "rpi" ]; then \
      # prepare qemu
      docker run --rm --privileged multiarch/qemu-user-static:register --reset; \
    fi; \
    docker-compose build;
  # push image
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";    
  - docker push "$DOCKER_USER"/magicmirror:"$BuildEnv"_"$MagicMirror_Version";
  - docker tag "$DOCKER_USER"/magicmirror:"$BuildEnv"_"$MagicMirror_Version" "$DOCKER_USER"/magicmirror:"$BuildEnv";
  - docker push "$DOCKER_USER"/magicmirror:"$BuildEnv";
  - cd ..
  - |
    SLIM_PARAMS="--http-probe --env BuildEnv=$BuildEnv --include-path /bin --include-path /opt/magic_mirror --entrypoint /opt/magic_mirror/slim-entrypoint.sh --tag $DOCKER_USER/magicmirror:$BuildEnv-slim $DOCKER_USER/magicmirror:$BuildEnv"
    if [ "$BuildEnv" = "rpi" ]; then \
      ./dist_linux/docker-slim build --continue-after timeout --env LD_LIBRARY_PATH=/opt/vc/lib --env DISPLAY=unix:0.0 --mount /tmp/.X11-unix:/tmp/.X11-unix --mount /opt/vc:/opt/vc/:ro --mount /run/systemd:/run/systemd --include-path /usr/share/fonts --include-path /etc/fonts --include-path /lib/arm-linux-gnueabihf --include-path /usr/lib/arm-linux-gnueabihf --include-path /usr/local/lib $SLIM_PARAMS; \
    else \
      ./dist_linux/docker-slim build --continue-after probe $SLIM_PARAMS; \
    fi;     
  - docker push "$DOCKER_USER"/magicmirror:"$BuildEnv"-slim;
  only:
  - master
  tags:
  - docker

build_debian:
  stage: build
  variables:
    MyBuildEnv: "debian"
  <<: *do_build

build_rpi:
  stage: build
  variables:
    MyBuildEnv: "rpi"
  <<: *do_build

after_script:
- docker logout