stages:
  - build
  - test

image: ${CI_REGISTRY}/khassel/container/kaniko:latest

variables:
  GIT_DEPTH: 1
  MAGICMIRROR_VERSION: "v2.15.0"
  NODE_VERSION_MASTER: "lts"
  NODE_VERSION_DEVELOP: "16"

.jobext:
  rules:
  - if: $CI_COMMIT_BRANCH =~ /^(master|develop)$/ && $TASK == "runtime"
  tags:
  - docker

build:
  stage: build
  script:
  - ./bin/build.sh
  extends: .jobext
  parallel:
    matrix:
      - imgarch: ["amd64", "arm", "arm64"]

# test raspi-image with gpio support and python
build_gpio:
  stage: build
  script:
  - |
    /register
    docker.gitlab.login
    build --context ./build \
      --dockerfile Dockerfile-gpio \
      --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}_gpio \
      --build-arg BASE_IMG=${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}_arm
  rules:
  - if: $CI_COMMIT_BRANCH =~ /^(master|develop)$/ && $TASK == "gpio"
  tags:
  - docker

test_amd64:
  stage: test
  needs: ["build: [amd64]"]
  variables:
    GIT_STRATEGY: none
    StartEnv: test
  image: 
    name: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}_amd64
    entrypoint: [""]
  script:
  - /opt/magic_mirror/entrypoint.sh
  extends: .jobext

snyk_amd64:
  stage: test
  image: 
    name: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_BRANCH}_amd64
    entrypoint: [""]
  script:
  - sudo npm install -g snyk snyk-to-html npm-check-updates
  - snyk auth ${SNYK_TOKEN}
  - cd /opt/magic_mirror
  - snyk test --json | snyk-to-html -o ${CI_PROJECT_DIR}/snyk_results.html || true
  - ncu
  rules:
  - if: $CI_COMMIT_BRANCH =~ /^(master|develop)$/ && $TASK == "snyk"
  tags:
  - docker
  artifacts:
    when: always
    paths: 
      - snyk_results.html

pages:
  stage: build
  image: ${CI_REGISTRY}/khassel/jekyll:latest
  script:
    - cp -v .gitlab-ci.yml ${CI_PROJECT_DIR}/pages/_data/gitlab.yml
    - uglify.sh ${CI_PROJECT_DIR}/pages/assets/js
    - cd pages
    - bundle exec jekyll build -d ${CI_PROJECT_DIR}/public
  artifacts:
    paths:
      - public
  rules:
  - if: ($CI_COMMIT_BRANCH =~ /^(master|develop)$/) && ($TASK == "pages" || $TASK == "runtime")
  tags:
  - docker
