stages:
  - build
#  - manifest
  - test

image: ${DOCKER_USER}/docker:stable

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: 1
  MagicMirror_Version: v2.10.0

services:
- docker:dind
#- name: docker:dind
#  command: ["--experimental"]

before_script:
- docker info
- |
  if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then \
    echo "branch=master"; \
  else \
    echo "branch<>master"; \
    export BuildRef="_test"; \
  fi;     

.whenrun:
  only:
  - master
  - develop
  tags:
  - docker

build:
  stage: build
  script:
  - echo "MagicMirror_Version="${MagicMirror_Version}
  - cd ./build
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker login -u=${DOCKER_USER} -p=${DOCKER_PASS}
  - docker buildx create --name xbuilder --use
  - docker buildx ls
  - docker buildx build --progress "plain" --platform "linux/amd64,linux/arm/v7" --build-arg "MagicMirror_Version=${MagicMirror_Version}" --build-arg "BuildRef=${BuildRef}" --push -t $DOCKER_USER/magicmirror:${MagicMirror_Version}${BuildRef} .
  - docker buildx build --progress "plain" --platform "linux/amd64,linux/arm/v7" --build-arg "MagicMirror_Version=${MagicMirror_Version}" --build-arg "BuildRef=${BuildRef}" --push -t $DOCKER_USER/magicmirror:latest${BuildRef} .
#  - cd ..
#  - docker run --rm --entrypoint cat ${DOCKER_USER}/magicmirror:${BuildEnv}_${MagicMirror_Version}${BuildRef} package-lock.json > package-lock.json
  # artifacts:
    # paths:
    # - package-lock.json
  extends: .whenrun

# manifest:
  # stage: manifest
  # script:
  # - docker pull ${DOCKER_USER}/magicmirror:rpi
  # - docker pull ${DOCKER_USER}/magicmirror:debian
  # - docker manifest create ${DOCKER_USER}/magicmirror:latest ${DOCKER_USER}/magicmirror:rpi ${DOCKER_USER}/magicmirror:debian
  # - docker manifest annotate --os linux --arch amd64 ${DOCKER_USER}/magicmirror:latest ${DOCKER_USER}/magicmirror:debian
  # - docker manifest annotate --os linux --arch arm ${DOCKER_USER}/magicmirror:latest ${DOCKER_USER}/magicmirror:rpi
  # - docker login -u=${DOCKER_USER} -p=${DOCKER_PASS}
  # - docker manifest push ${DOCKER_USER}/magicmirror:latest  
  # - update_docker_readme.sh magicmirror
  # only:
  # - master
  # tags:
  # - docker

test:
  stage: test
  script:
  - cd test
  - docker build --build-arg baseimage=${DOCKER_USER}/magicmirror:${MagicMirror_Version}${BuildRef} -t $DOCKER_USER/magicmirror:mm_tests .
  - docker run --rm --entrypoint cat ${DOCKER_USER}/magicmirror:mm_tests package-lock.json > package-lock.json
  - docker run --rm --privileged ${DOCKER_USER}/magicmirror:mm_tests
  artifacts:
    paths:
    - package-lock.json
  allow_failure: true
  extends: .whenrun

after_script:
- docker logout