stages:
  - build
  - test

image: ${DOCKER_USER}/kaniko-executor:latest

variables:
  GIT_DEPTH: 1

.jobext:
  after_script:
  - docker.logout
  rules:
  - if: $CI_COMMIT_BRANCH =~ /^(master|develop)$/
  tags:
  - docker

build:
  stage: build
  script:
  - ./bin/build.sh ${CI_COMMIT_BRANCH} ${imgarch}
  extends: .jobext
  parallel:
    matrix:
      - imgarch: ["amd64", "arm"]

build_alpine:
  stage: test
  needs: ["build: [amd64]"]
  script:
  - ./bin/build_alpine.sh ${CI_COMMIT_BRANCH}
  extends: .jobext

test_amd64:
  stage: test
  needs: ["build: [amd64]"]
  variables:
    GIT_STRATEGY: none
    StartEnv: test
  image: 
    name: ${DOCKER_USER}/magicmirror:${CI_COMMIT_BRANCH}_amd64
    entrypoint: [""]
  script:
  - /opt/magic_mirror/entrypoint.sh
  extends: .jobext
