sudo: required
services:
- docker
language: bash
env:
- BuildEnv=rpi
- BuildEnv=debian
before_script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
script:
- ./prepare_env $BuildEnv
# get variables from .env
- export $(cat .env | grep -v ^# | xargs)
- echo "BuildEnv="$BuildEnv;
- echo "myimage="$myimage;
- echo "MagicMirror_Version="$MagicMirror_Version;
# build image
- cd ./build
- docker-compose build
# push image
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";    
- docker push "$DOCKER_USER"/magicmirror:"$BuildEnv"_"$MagicMirror_Version";
- docker tag "$DOCKER_USER"/magicmirror:"$BuildEnv"_"$MagicMirror_Version" "$DOCKER_USER"/magicmirror:"$BuildEnv";
- docker push "$DOCKER_USER"/magicmirror:"$BuildEnv";
after_script:
- docker logout
