sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker-compose build
# test image
- cd ./up-serveronly
- docker-compose up -d
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push karsten13/mm_hyp:$TRAVIS_TAG
    docker tag karsten13/mm_hyp:$TRAVIS_TAG karsten13/mm_hyp:latest
  fi