version: '3'

# for build only
services:
  mm_serveronly:
    build: 
      context: ./
      args: 
        MagicMirror_Version: ${MagicMirror_Version}
    container_name: mm
    image: karsten13/mm_hyp:latest