services:
  base:
    image: ${MM_IMAGE}
    volumes:
      - ../../mounts/config:/opt/magic_mirror/config
      - ../../mounts/modules:/opt/magic_mirror/modules
      - ../../mounts/css:/opt/magic_mirror/css
  base_init:
    depends_on:
      init:
        condition: service_completed_successfully
    extends:
      service: base
  server_no_init:
    environment:
      MM_OVERRIDE_DEFAULT_MODULES: ${MM_OVERRIDE_DEFAULT_MODULES}
      MM_OVERRIDE_CSS: ${MM_OVERRIDE_CSS}
      MM_SHOW_CURSOR: ${MM_SHOW_CURSOR}
      MM_SCENARIO: ${MM_SCENARIO}
    ports:
      - ${MM_SERVER_PORTS}
    extends:
      service: base
  server_init:
    depends_on:
      init:
        condition: service_completed_successfully
    extends:
      service: server_no_init
  electron_no_init:
    extends:
      service: base
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/node/.Xauthority
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    privileged: true # avoids dbus errors in logs
    devices:
      - /dev/vchiq
    environment:
      DISPLAY: unix:0.0
      MM_OVERRIDE_DEFAULT_MODULES: ${MM_OVERRIDE_DEFAULT_MODULES}
      MM_OVERRIDE_CSS: ${MM_OVERRIDE_CSS}
      MM_SHOW_CURSOR: ${MM_SHOW_CURSOR}
      MM_SCENARIO: ${MM_SCENARIO}
    network_mode: host
    shm_size: "128mb"
  electron_init:
    depends_on:
      init:
        condition: service_completed_successfully
    extends:
      service: electron_no_init
  client_no_init:
    image: ${MM_IMAGE}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    privileged: true # avoids dbus errors in logs
    environment:
      DISPLAY: unix:0.0
    shm_size: "128mb"
    command: "node clientonly --address ${MM_CLIENT_ADDRESS} --port ${MM_CLIENT_PORT}"
