services:
  fedora:
    image: karsten13/magicmirror:fedora
    volumes:
      - ${VOLUME_CONFIG}:z
      - ${VOLUME_MODULES}:z
      - ${VOLUME_CSS}:z
      - /tmp/.X11-unix:/tmp/.X11-unix:z
    privileged: true
    environment:
      - DISPLAY=unix:0.0
