services:
  mmpm:
    container_name: mmpm
    image: karsten13/mmpm:latest
    depends_on:
      magicmirror:
        condition: service_started
    ports:
      - "7890:7890"
      - "7891:7891"
      - "6789:6789"
      - "8907:8907"
    volumes:
      - ../mounts/modules:/home/node/MagicMirror/modules
      - ../mounts/config:/home/node/MagicMirror/config
      - ../mounts/css:/home/node/MagicMirror/css
      - ../mounts/mmpm-config:/home/node/.config/mmpm
    restart: unless-stopped
