services:
  xserver:
    container_name: xserver
    image: karsten13/xserver:latest
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:z
    environment:
      DISPLAY: :0.0
      XRANDR_PARAMS: "${XRANDR_PARAMS}"
    restart: unless-stopped
