version: '3'

services:
  mm_serveronly:
    container_name: mm
    image: karsten13/mm_hyp:latest
    ports:
      - "8080:8080"
    volumes:
      - ../../MagicMirror/config:/opt/magic_mirror/config
      - ../../MagicMirror/modules:/opt/magic_mirror/modules
    entrypoint: /opt/magic_mirror/docker-entrypoint.sh "node serveronly"