version: '3'

services:
  volumepermissions:
    container_name: alpine
    image: alpine:latest
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
    entrypoint: "chown -R 1000:1000 /opt/magic_mirror/modules/ && chown -R 1000:1000 /opt/magic_mirror/config/"

  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    depends_on:
      - volumepermissions
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
      - /run/systemd:/run/systemd
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
      TZ: Europe/Berlin
    network_mode: host
    restart: unless-stopped
    command: 
      - npm
      - start