version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - mm-volume:/opt/magic_mirror
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
    devices:
      - /dev/vchiq
    environment:
      LD_LIBRARY_PATH: /opt/vc/lib
      DISPLAY: unix:0.0
      TZ: Europe/Berlin
    network_mode: host
    restart: unless-stopped
    command:
      - npm
      - run
      - start

  mmpm:
    container_name: mmpm
    image: karsten13/mmpm:latest
    depends_on:
      - magicmirror
    ports:
      - "7890:7890"
      - "7892:7892"
    volumes:
      - ../mounts/modules:/home/node/MagicMirror/modules
      - ../mounts/config:/home/node/MagicMirror/config
      - mm-volume:/home/node/MagicMirror:ro
    restart: unless-stopped

volumes:
  mm-volume: