x-common: &common
  image: karsten13/magicmirror:latest
  volumes:
    - ../mounts/config:/opt/magic_mirror/config
    - ../mounts/modules:/opt/magic_mirror/modules
    - ../mounts/css:/opt/magic_mirror/css

services:
  init:
    <<: *common
    container_name: init
    user: root
    environment:
      STARTENV: init
  magicmirror:
    <<: *common
    container_name: mm
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    restart: unless-stopped
  mmpm:
    container_name: mmpm
    image: karsten13/mmpm:latest
    depends_on:
      magicmirror:
        condition: service_started
    ports:
      - "7890:7890"
      - "7891:7891"
      - "6789:6789"
      - "8907:8907"
    volumes:
      - ../mounts/modules:/home/node/MagicMirror/modules
      - ../mounts/config:/home/node/MagicMirror/config
      - ../mounts/css:/home/node/MagicMirror/css
      - ../mounts/mmpm-config:/home/node/.config/mmpm
    restart: unless-stopped
