version: '3'

services:
  magicmirror:
    container_name: mm
    image: karsten13/magicmirror:latest
    ports:
      - "8080:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Europe/Berlin
    restart: unless-stopped
    command: 
      - npm
      - run
      - server
